const CONFIG = {
    titleWeb: "Xin lỗi bé",
    introTitle: 'Nguyễn Thanh Quỳnh Như',
    introDesc: `Anh muốn thành tâm xin nỗi cục cưng của anh`,
    btnIntro: '^^HiHi^^',
    title: 'Anh xin lỗi vì đã nói chuyện không hợp ý em',
    desc: 'Em thông cảm cho anh vì hiện tại anh đang không được khỏe lắm em nhé 😙',
    btnYes: 'Hong giận nữa',
    btnNo: 'Vẫn giận anh luôn',
    question: 'Zạy em muốn anh làm gì cho em hết giận nè',
    btnReply: 'Gửi cho anh <3',
    reply: 'Anh phải thay đổi mới được',
    mess: 'Anh biết gòi hihi, anh thương bé nhìu',
    messDesc: 'Mình làm hòa em nhé',
    btnAccept: 'Okiiiii lun <3',
}
